import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { savePdfReliably } from "./pdf-save";

const MARGIN = 25.4; // 1 inch for binder compatibility
const R_MARGIN = 25.4; // 1 inch right margin — matches left for binder compatibility

export interface BillOfSaleData {
  companyName: string;
  sellerName: string;
  buyerName: string;
  numShares: number;
  shareClass: string;
  pricePerShare?: number | null;
  totalPrice?: number | null;
  saleDate: string;
  considerationType?: string;
  certificateNumber?: number | null;
  assets?: { description: string; value: number }[];
}

export function generateBillOfSalePdf(data: BillOfSaleData): jsPDF {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text("BILL OF SALE", pw / 2, 25, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(data.companyName, pw / 2, 33, { align: "center" });

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, 38, pw - R_MARGIN, 38);

  let y = 48;

  // Transaction details table
  const details = [
    ["Date of Sale", new Date(data.saleDate + "T00:00:00").toLocaleDateString()],
    ["Seller", data.sellerName],
    ["Buyer", data.buyerName],
    ["Share Class", data.shareClass],
    ["Number of Shares", data.numShares.toLocaleString()],
  ];

  if (data.pricePerShare != null) {
    details.push(["Price Per Share", `$${Number(data.pricePerShare).toFixed(2)}`]);
  }
  if (data.totalPrice != null) {
    details.push(["Total Consideration", `$${Number(data.totalPrice).toFixed(2)}`]);
  }
  if (data.considerationType) {
    details.push(["Consideration Type", data.considerationType.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase())]);
  }
  if (data.certificateNumber != null) {
    details.push(["Certificate Number", `#${data.certificateNumber}`]);
  }

  autoTable(doc, {
    startY: y,
    head: [["Field", "Value"]],
    body: details,
    theme: "grid",
    headStyles: { fillColor: [45, 55, 72], fontSize: 9, fontStyle: "bold" },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 55, fontStyle: "bold" } },
    margin: { left: MARGIN, right: R_MARGIN },
  });

  y = (doc as any).lastAutoTable.finalY + 12;

  // Asset grid if present
  if (data.assets && data.assets.length > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Non-Cash Consideration — Asset Detail", MARGIN, y);
    y += 6;

    const assetRows = data.assets.map(a => [a.description, `$${a.value.toFixed(2)}`]);
    const assetTotal = data.assets.reduce((sum, a) => sum + a.value, 0);
    assetRows.push(["TOTAL", `$${assetTotal.toFixed(2)}`]);

    autoTable(doc, {
      startY: y,
      head: [["Description", "Value"]],
      body: assetRows,
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 9, fontStyle: "bold" },
      bodyStyles: { fontSize: 9 },
      margin: { left: MARGIN, right: R_MARGIN },
      didParseCell(cellData) {
        if (cellData.section === "body" && cellData.row.index === assetRows.length - 1) {
          cellData.cell.styles.fontStyle = "bold";
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 12;
  }

  // Legal text
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  const legalText = `FOR VALUE RECEIVED, the undersigned Seller hereby sells, assigns, and transfers to the Buyer the above-described shares of ${data.companyName}, together with all rights, title, and interest therein.`;
  const legalLines = doc.splitTextToSize(legalText, pw - MARGIN - R_MARGIN);
  doc.text(legalLines, MARGIN, y);
  y += legalLines.length * 5 + 20;

  // Signature lines
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, 90, y);
  doc.line(pw / 2 + 10, y, pw - R_MARGIN, y);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Seller Signature", 52, y + 5, { align: "center" });
  doc.text("Buyer Signature", (pw / 2 + 10 + pw - R_MARGIN) / 2, y + 5, { align: "center" });
  y += 15;
  doc.line(MARGIN, y, 90, y);
  doc.line(pw / 2 + 10, y, pw - R_MARGIN, y);
  doc.text("Date", 52, y + 5, { align: "center" });
  doc.text("Date", (pw / 2 + 10 + pw - R_MARGIN) / 2, y + 5, { align: "center" });

  // Footer
  const ph = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by EntityIQ — Corporate Records Management", pw / 2, ph - 10, { align: "center" });

  return doc;
}

export function downloadBillOfSalePdf(data: BillOfSaleData) {
  const doc = generateBillOfSalePdf(data);
  const filename = `bill-of-sale-${data.saleDate}.pdf`;
  doc.save(filename);
}
