import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Wisconsin DFI-style document formatting
const DFI_HEADER = "STATE OF WISCONSIN";
const DFI_SUB = "DEPARTMENT OF FINANCIAL INSTITUTIONS";

interface MeetingData {
  meeting: any;
  company: any;
  shareholders?: any[];
  directors?: any[];
  officers?: any[];
  counsel?: any[];
  assets?: any[];
  amendments?: any[];
  resolutions?: any[];
  benefits?: any[];
  loans?: any[];
  agreements?: any[];
  other?: any[];
  financials?: any;
  authorizedSigners?: any[];
}

function addDFIHeader(doc: jsPDF, title: string, companyName: string, entityType: string) {
  const pw = doc.internal.pageSize.getWidth();
  const cx = pw / 2;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(DFI_HEADER, cx, 16, { align: "center" });

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(DFI_SUB, cx, 21, { align: "center" });

  doc.setDrawColor(30, 30, 30);
  doc.setLineWidth(0.8);
  doc.line(14, 25, pw - 14, 25);
  doc.setLineWidth(0.3);
  doc.line(14, 26.5, pw - 14, 26.5);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(title.toUpperCase(), cx, 35, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text(`${companyName} — ${entityType}`, cx, 41, { align: "center" });

  doc.setLineWidth(0.3);
  doc.setDrawColor(160, 160, 160);
  doc.line(14, 45, pw - 14, 45);
}

function addDFIFooter(doc: jsPDF, companyName: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const ph = doc.internal.pageSize.getHeight();
    const pw = doc.internal.pageSize.getWidth();

    doc.setDrawColor(160, 160, 160);
    doc.setLineWidth(0.3);
    doc.line(14, ph - 18, pw - 14, ph - 18);

    doc.setFontSize(7);
    doc.setTextColor(130, 130, 130);
    doc.text(`${companyName} — Corporate Records`, 14, ph - 13);
    doc.text(`Page ${i} of ${pageCount}`, pw - 14, ph - 13, { align: "right" });
    doc.text("Generated by EntityIQ", 14, ph - 9);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pw - 14, ph - 9, { align: "right" });
  }
}

function addSectionTitle(doc: jsPDF, y: number, title: string): number {
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(title.toUpperCase(), 14, y);
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(14, y + 1.5, doc.internal.pageSize.getWidth() - 14, y + 1.5);
  return y + 6;
}

function addLabelValue(doc: jsPDF, y: number, label: string, value: string, x = 14): number {
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80, 80, 80);
  doc.text(`${label}:`, x, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  doc.text(value || "—", x + doc.getTextWidth(`${label}: `) + 2, y);
  return y + 5;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > doc.internal.pageSize.getHeight() - 25) {
    doc.addPage();
    return 20;
  }
  return y;
}

export function exportMeetingMinutesPDF(data: MeetingData) {
  const doc = new jsPDF();
  const { meeting, company } = data;
  const companyName = company?.name || "Unknown Company";
  const entityType = company?.entity_type || "Corporation";
  const meetingDate = new Date(meeting.meeting_date + "T00:00:00").toLocaleDateString();

  addDFIHeader(doc, `${meeting.meeting_type} — Minutes`, companyName, entityType);

  let y = 52;

  // Meeting Info Section
  y = addSectionTitle(doc, y, "Meeting Information");
  y = addLabelValue(doc, y, "Date", meetingDate);
  y = addLabelValue(doc, y, "Type", `${meeting.meeting_type}${meeting.sub_type ? ` — ${meeting.sub_type}` : ""}`);
  if (meeting.meeting_time) y = addLabelValue(doc, y, "Time", meeting.meeting_time);
  if (meeting.meeting_location) y = addLabelValue(doc, y, "Location", meeting.meeting_location);

  // Smart chairperson/secretary paragraph: combine if same person
  const chair = meeting.chairperson?.trim() || "";
  const sec = meeting.mtg_secretary?.trim() || "";
  if (chair && sec && chair.toLowerCase() === sec.toLowerCase()) {
    y = addLabelValue(doc, y, "Chairperson & Secretary", chair);
  } else {
    if (chair) y = addLabelValue(doc, y, "Chairperson", chair);
    if (sec) y = addLabelValue(doc, y, "Secretary", sec);
  }

  if (meeting.tax_year) y = addLabelValue(doc, y, "Tax Year", String(meeting.tax_year));
  if (meeting.others_present) y = addLabelValue(doc, y, "Others Present", meeting.others_present);

  // Company Info
  y += 3;
  y = addSectionTitle(doc, y, "Company Information at Time of Meeting");
  y = addLabelValue(doc, y, "Company Name", meeting.company_name_at_meeting || companyName);
  const addr = [meeting.company_address_at_meeting, meeting.company_city_at_meeting, meeting.company_state_at_meeting, meeting.company_zip_at_meeting].filter(Boolean).join(", ");
  if (addr) y = addLabelValue(doc, y, "Address", addr);

  // Directors
  if (data.directors && data.directors.length > 0) {
    y += 3;
    y = checkPageBreak(doc, y, 20 + data.directors.length * 7);
    y = addSectionTitle(doc, y, "Directors Present");
    autoTable(doc, {
      startY: y,
      head: [["Director Name"]],
      body: data.directors.map(d => [d.director_name]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Officers (with salary/bonus)
  if (data.officers && data.officers.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.officers.length * 7);
    y = addSectionTitle(doc, y, "Officers");
    const hasSalaryData = data.officers.some(o => o.salary != null || o.bonus != null);
    autoTable(doc, {
      startY: y,
      head: [hasSalaryData ? ["Title", "Name", "Salary", "Bonus"] : ["Title", "Name"]],
      body: data.officers.map(o => hasSalaryData
        ? [o.title, o.name, o.salary != null ? fmt(o.salary) : "—", o.bonus != null ? fmt(o.bonus) : "—"]
        : [o.title, o.name]
      ),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Shareholders
  if (data.shareholders && data.shareholders.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.shareholders.length * 7);
    y = addSectionTitle(doc, y, entityType === "LLC" ? "Members" : "Shareholders");
    autoTable(doc, {
      startY: y,
      head: [["Name", "Common Shares", "Preferred Shares", "Distribution"]],
      body: data.shareholders.map(s => [
        s.shareholder_name,
        s.common_shares?.toLocaleString() ?? "—",
        s.preferred_shares?.toLocaleString() ?? "—",
        s.distribution || "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Financials
  if (data.financials) {
    const f = data.financials;
    y = checkPageBreak(doc, y, 50);
    y = addSectionTitle(doc, y, "Financial Comparison");
    autoTable(doc, {
      startY: y,
      head: [["", "Current Year", "Previous Year"]],
      body: [
        ["Total Sales", fmt(f.current_total_sales), fmt(f.previous_total_sales)],
        ["Cost of Goods", fmt(f.current_cog), fmt(f.previous_cog)],
        ["Gross Profit", fmt(f.current_gross_profit), fmt(f.previous_gross_profit)],
        ["COG Ratio (%)", f.current_cog_ratio != null ? `${Number(f.current_cog_ratio).toFixed(2)}%` : "—", f.previous_cog_ratio != null ? `${Number(f.previous_cog_ratio).toFixed(2)}%` : "—"],
        ["Net Income", fmt(f.current_net_income), fmt(f.previous_net_income)],
      ],
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      columnStyles: { 1: { halign: "right", fontStyle: "bold" }, 2: { halign: "right" } },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Counsel
  if (data.counsel && data.counsel.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.counsel.length * 7);
    y = addSectionTitle(doc, y, "Counsel / Banking / Loans");
    autoTable(doc, {
      startY: y,
      head: [["Counsel", "Bank", "Loans"]],
      body: data.counsel.map(c => [c.counsel_name || "—", c.bank_name || "—", c.loans || "—"]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Loans
  if (data.loans && data.loans.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.loans.length * 7);
    y = addSectionTitle(doc, y, "Loans");
    autoTable(doc, {
      startY: y,
      head: [["Type", "Rate", "Amount", "Date", "Notes"]],
      body: data.loans.map(l => [
        l.loan_type || "—",
        l.loan_rate != null ? `${Number(l.loan_rate).toFixed(2)}%` : "—",
        l.loan_amount != null ? fmt(l.loan_amount) : "—",
        l.loan_date ? new Date(l.loan_date + "T00:00:00").toLocaleDateString() : "—",
        l.notes || "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Assets
  if (data.assets && data.assets.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.assets.length * 7);
    y = addSectionTitle(doc, y, "Assets");
    autoTable(doc, {
      startY: y,
      head: [["Type", "Description", "Value"]],
      body: data.assets.map(a => [a.asset_type, a.description, a.value != null ? `$${Number(a.value).toLocaleString(undefined, { minimumFractionDigits: 2 })}` : "—"]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Amendments
  if (data.amendments && data.amendments.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.amendments.length * 12);
    y = addSectionTitle(doc, y, "Amendments");
    data.amendments.forEach((a) => {
      y = checkPageBreak(doc, y, 20);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(a.amendment_type || "Amendment", 14, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const lines = doc.splitTextToSize(a.amendment_text || "", doc.internal.pageSize.getWidth() - 28);
      doc.text(lines, 14, y);
      y += lines.length * 4 + 4;
    });
  }

  // Resolutions
  if (data.resolutions && data.resolutions.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.resolutions.length * 15);
    y = addSectionTitle(doc, y, "Resolutions");
    data.resolutions.forEach((r) => {
      y = checkPageBreak(doc, y, 25);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(r.purpose, 14, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const lines = doc.splitTextToSize(r.resolution_text || "", doc.internal.pageSize.getWidth() - 28);
      doc.text(lines, 14, y);
      y += lines.length * 4 + 4;
    });
  }

  // Benefits
  if (data.benefits && data.benefits.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.benefits.length * 7);
    y = addSectionTitle(doc, y, "Benefits");
    autoTable(doc, {
      startY: y,
      head: [["Benefit Type", "Provider", "Agent/Admin", "Plan Year", "Contribution"]],
      body: data.benefits.map(b => [
        b.benefit_type || b.benefit_description || "—",
        b.provider || "—",
        b.agent_administrator || "—",
        b.plan_year?.toString() || "—",
        b.retirement_contribution != null ? fmt(b.retirement_contribution) : "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Agreements
  if (data.agreements && data.agreements.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.agreements.length * 7);
    y = addSectionTitle(doc, y, "Agreements");
    autoTable(doc, {
      startY: y,
      head: [["Type", "Date", "With", "Purpose"]],
      body: data.agreements.map(a => [
        a.agreement_type,
        a.agreement_date ? new Date(a.agreement_date + "T00:00:00").toLocaleDateString() : "—",
        a.agreement_with || "—",
        a.agreement_purpose || "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Other
  if (data.other && data.other.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.other.length * 7);
    y = addSectionTitle(doc, y, "Other Notes");
    autoTable(doc, {
      startY: y,
      head: [["Notes"]],
      body: data.other.map(o => [o.notes]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Authorized Signatories
  if (data.authorizedSigners && data.authorizedSigners.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.authorizedSigners.length * 7);
    y = addSectionTitle(doc, y, "Authorized Signatories");
    autoTable(doc, {
      startY: y,
      head: [["Name", "Title", "Bank"]],
      body: data.authorizedSigners.map(s => [s.signer_name, s.title || "—", s.bank_name || "—"]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Signature block
  y = checkPageBreak(doc, y, 50);
  y += 8;
  doc.setDrawColor(160, 160, 160);
  doc.setLineWidth(0.3);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text("There being no further business, the meeting was adjourned.", 14, y);
  y += 12;

  doc.line(14, y, 90, y);
  doc.text("Secretary", 14, y + 4);
  doc.text("Date: _______________", 95, y + 4);

  y += 14;

  doc.line(14, y, 90, y);
  doc.text("Chairperson", 14, y + 4);
  doc.text("Date: _______________", 95, y + 4);

  addDFIFooter(doc, companyName);
  return doc;
}

// Export individual section PDFs
export function exportSectionPDF(
  sectionTitle: string,
  company: any,
  meeting: any,
  tableHead: string[],
  tableBody: string[][],
) {
  const doc = new jsPDF();
  const companyName = company?.name || "Unknown";
  const entityType = company?.entity_type || "Corporation";
  const meetingDate = new Date(meeting.meeting_date + "T00:00:00").toLocaleDateString();

  addDFIHeader(doc, sectionTitle, companyName, entityType);

  let y = 52;
  y = addLabelValue(doc, y, "Meeting Date", meetingDate);
  y = addLabelValue(doc, y, "Meeting Type", meeting.meeting_type);
  if (meeting.tax_year) y = addLabelValue(doc, y, "Tax Year", String(meeting.tax_year));
  y += 3;

  if (tableBody.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [tableHead],
      body: tableBody,
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
      styles: { overflow: "linebreak", cellWidth: "auto" },
    });
  } else {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(130, 130, 130);
    doc.text("No records to display.", 14, y + 6);
  }

  addDFIFooter(doc, companyName);
  return doc;
}

export function exportAmendmentsPDF(company: any, meeting: any, amendments: any[]) {
  return exportSectionPDF(
    "Amendments",
    company,
    meeting,
    ["Amendment Type", "Details"],
    amendments.map(a => [a.amendment_type || "—", a.amendment_text || "—"]),
  );
}

export function exportResolutionsPDF(company: any, meeting: any, resolutions: any[]) {
  return exportSectionPDF(
    "Resolutions",
    company,
    meeting,
    ["Purpose", "Resolution Text"],
    resolutions.map(r => [r.purpose, r.resolution_text]),
  );
}

export function exportFinancialsPDF(company: any, meeting: any, financials: any) {
  const doc = new jsPDF();
  const companyName = company?.name || "Unknown";
  const entityType = company?.entity_type || "Corporation";
  const meetingDate = new Date(meeting.meeting_date + "T00:00:00").toLocaleDateString();

  addDFIHeader(doc, "Financial Comparison", companyName, entityType);

  let y = 52;
  y = addLabelValue(doc, y, "Meeting Date", meetingDate);
  if (meeting.tax_year) y = addLabelValue(doc, y, "Tax Year", String(meeting.tax_year));
  y += 3;

  if (financials) {
    // YoY helper
    const yoy = (cur: any, prev: any): string => {
      if (cur == null || prev == null || prev === 0) return "";
      const pct = ((Number(cur) - Number(prev)) / Math.abs(Number(prev))) * 100;
      return `${pct >= 0 ? "▲" : "▼"} ${Math.abs(pct).toFixed(1)}%`;
    };

    autoTable(doc, {
      startY: y,
      head: [["", "Current Year", "Previous Year", "YoY Change"]],
      body: [
        ["Total Sales", fmt(financials.current_total_sales), fmt(financials.previous_total_sales), yoy(financials.current_total_sales, financials.previous_total_sales)],
        ["Cost of Goods", fmt(financials.current_cog), fmt(financials.previous_cog), yoy(financials.current_cog, financials.previous_cog)],
        ["Gross Profit", fmt(financials.current_gross_profit), fmt(financials.previous_gross_profit), yoy(financials.current_gross_profit, financials.previous_gross_profit)],
        ["COG Ratio (%)", financials.current_cog_ratio != null ? `${Number(financials.current_cog_ratio).toFixed(2)}%` : "—", financials.previous_cog_ratio != null ? `${Number(financials.previous_cog_ratio).toFixed(2)}%` : "—", yoy(financials.current_cog_ratio, financials.previous_cog_ratio)],
        ["Net Income", fmt(financials.current_net_income), fmt(financials.previous_net_income), yoy(financials.current_net_income, financials.previous_net_income)],
      ],
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      columnStyles: { 1: { halign: "right", fontStyle: "bold" }, 2: { halign: "right" }, 3: { halign: "center", fontSize: 7 } },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;

    // Draw simple bar chart comparison
    const pw = doc.internal.pageSize.getWidth();
    y = checkPageBreak(doc, y, 90);
    y = addSectionTitle(doc, y, "Visual Comparison");

    const chartItems = [
      { label: "Total Sales", cur: Number(financials.current_total_sales) || 0, prev: Number(financials.previous_total_sales) || 0 },
      { label: "Gross Profit", cur: Number(financials.current_gross_profit) || 0, prev: Number(financials.previous_gross_profit) || 0 },
      { label: "COG", cur: Number(financials.current_cog) || 0, prev: Number(financials.previous_cog) || 0 },
      { label: "Net Income", cur: Number(financials.current_net_income) || 0, prev: Number(financials.previous_net_income) || 0 },
    ];

    const maxVal = Math.max(...chartItems.map(i => Math.max(Math.abs(i.cur), Math.abs(i.prev))), 1);
    const barMaxWidth = pw - 80;
    const barHeight = 6;
    const groupHeight = 22;

    // Legend
    doc.setFillColor(45, 55, 120);
    doc.rect(14, y, 8, 4, "F");
    doc.setFontSize(7);
    doc.setTextColor(80, 80, 80);
    doc.text("Current Year", 24, y + 3);
    doc.setFillColor(160, 160, 180);
    doc.rect(60, y, 8, 4, "F");
    doc.text("Previous Year", 70, y + 3);
    y += 10;

    chartItems.forEach((item) => {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 60);
      doc.text(item.label, 14, y + 3);

      const curWidth = maxVal > 0 ? (Math.abs(item.cur) / maxVal) * barMaxWidth : 0;
      const prevWidth = maxVal > 0 ? (Math.abs(item.prev) / maxVal) * barMaxWidth : 0;

      doc.setFillColor(45, 55, 120);
      doc.roundedRect(50, y - 2, Math.max(curWidth, 1), barHeight, 1, 1, "F");

      doc.setFillColor(160, 160, 180);
      doc.roundedRect(50, y + barHeight, Math.max(prevWidth, 1), barHeight, 1, 1, "F");

      // Values
      doc.setFontSize(6);
      doc.setTextColor(30, 30, 30);
      if (item.cur > 0) doc.text(fmt(item.cur), 50 + curWidth + 2, y + 3);
      if (item.prev > 0) doc.text(fmt(item.prev), 50 + prevWidth + 2, y + barHeight + 5);

      y += groupHeight;
    });
  }

  addDFIFooter(doc, companyName);
  return doc;
}

function fmt(val: any): string {
  if (val == null) return "—";
  return `$${Number(val).toLocaleString(undefined, { minimumFractionDigits: 2 })}`;
}

// Save and download
export function downloadPDF(doc: jsPDF, fileName: string) {
  doc.save(fileName);
}

// Get PDF as blob URL for preview
export function getPDFPreviewUrl(doc: jsPDF): string {
  const blob = doc.output("blob");
  return URL.createObjectURL(blob);
}
