import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Wisconsin DFI-style document formatting
const DFI_HEADER = "STATE OF WISCONSIN";
const DFI_SUB = "DEPARTMENT OF FINANCIAL INSTITUTIONS";

interface MeetingData {
  meeting: any;
  company: any;
  shareholders?: any[];
  directors?: any[];
  officers?: any[];
  counsel?: any[];
  assets?: any[];
  amendments?: any[];
  resolutions?: any[];
  benefits?: any[];
  loans?: any[];
  agreements?: any[];
  other?: any[];
  financials?: any;
  authorizedSigners?: any[];
  priorYear?: {
    officers?: any[];
    benefits?: any[];
    loans?: any[];
    authorizedSigners?: any[];
  };
}

function addDFIHeader(doc: jsPDF, title: string, companyName: string, entityType: string, meeting?: any, company?: any) {
  const pw = doc.internal.pageSize.getWidth();
  const cx = pw / 2;

  // Company name as top header (letterhead style)
  const displayName = meeting?.company_name_at_meeting || companyName;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(displayName, cx, 16, { align: "center" });

  // Address line
  const addrLine = meeting?.company_address_at_meeting || company?.address || "";
  let hy = 21;
  if (addrLine) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(addrLine, cx, hy, { align: "center" });
    hy += 5;
  }

  // City, State Zip
  const cityPart = meeting?.company_city_at_meeting || company?.city || "";
  const statePart = meeting?.company_state_at_meeting || company?.state || "";
  const zipPart = meeting?.company_zip_at_meeting || company?.zip || "";
  const cityStateLine = [cityPart, statePart].filter(Boolean).join(", ") + (zipPart ? `  ${zipPart}` : "");
  if (cityStateLine.trim()) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(cityStateLine, cx, hy, { align: "center" });
    hy += 5;
  }

  hy += 1;
  doc.setDrawColor(30, 30, 30);
  doc.setLineWidth(0.8);
  doc.line(14, hy, pw - 14, hy);
  doc.setLineWidth(0.3);
  doc.line(14, hy + 1.5, pw - 14, hy + 1.5);
}

function addMeetingTypeHeader(doc: jsPDF, y: number, meetingType: string, companyName: string, meetingDate: string, isWrittenConsent: boolean): number {
  const pw = doc.internal.pageSize.getWidth();
  const cx = pw / 2;

  if (isWrittenConsent) {
    // Written Consent Header
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("WRITTEN CONSENT", cx, y, { align: "center" });
    y += 5;
    doc.setFontSize(10);
    doc.text("IN LIEU OF A MEETING", cx, y, { align: "center" });
    y += 5;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(`OF THE BOARD OF DIRECTORS / MEMBERS OF`, cx, y, { align: "center" });
    y += 5;
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(companyName.toUpperCase(), cx, y, { align: "center" });
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(`Date: ${meetingDate}`, cx, y, { align: "center" });
    y += 4;
    doc.setDrawColor(160, 160, 160);
    doc.setLineWidth(0.3);
    doc.line(14, y, pw - 14, y);
    y += 5;
    // Intro paragraph
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const introText = `The undersigned, being all of the directors/members of ${companyName}, do hereby consent to and adopt the following resolutions and actions without a formal meeting, pursuant to the applicable provisions of the Wisconsin Statutes:`;
    const lines = doc.splitTextToSize(introText, pw - 28);
    doc.text(lines, 14, y);
    y += lines.length * 4 + 4;
  } else {
    // Standard Meeting Type Header
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(`MINUTES OF ${meetingType.toUpperCase()}`, cx, y, { align: "center" });
    y += 5;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(`${companyName} — ${meetingDate}`, cx, y, { align: "center" });
    y += 4;
    doc.setDrawColor(160, 160, 160);
    doc.setLineWidth(0.3);
    doc.line(14, y, pw - 14, y);
    y += 5;
  }
  return y;
}

function addDFIFooter(doc: jsPDF, companyName: string) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const ph = doc.internal.pageSize.getHeight();
    const pw = doc.internal.pageSize.getWidth();

    doc.setDrawColor(160, 160, 160);
    doc.setLineWidth(0.3);
    doc.line(14, ph - 18, pw - 14, ph - 18);

    doc.setFontSize(7);
    doc.setTextColor(130, 130, 130);
    doc.text(`${companyName} — Corporate Records`, 14, ph - 13);
    doc.text(`Page ${i} of ${pageCount}`, pw - 14, ph - 13, { align: "right" });
    doc.text("Generated by EntityIQ", 14, ph - 9);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pw - 14, ph - 9, { align: "right" });
  }
}

function addSectionTitle(doc: jsPDF, y: number, title: string): number {
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(title.toUpperCase(), 14, y);
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(14, y + 1.5, doc.internal.pageSize.getWidth() - 14, y + 1.5);
  return y + 6;
}

function addLabelValue(doc: jsPDF, y: number, label: string, value: string, x = 14): number {
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80, 80, 80);
  doc.text(`${label}:`, x, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  doc.text(value || "—", x + doc.getTextWidth(`${label}: `) + 2, y);
  return y + 5;
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > doc.internal.pageSize.getHeight() - 25) {
    doc.addPage();
    return 20;
  }
  return y;
}

export function exportMeetingMinutesPDF(data: MeetingData) {
  const doc = new jsPDF();
  const { meeting, company } = data;
  const companyName = company?.name || "Unknown Company";
  const entityType = company?.entity_type || "Corporation";
  const meetingDate = new Date(meeting.meeting_date + "T00:00:00").toLocaleDateString();
  const isWrittenConsent = meeting.meeting_type === "Written Consent";

  addDFIHeader(doc, isWrittenConsent ? "Written Consent" : `${meeting.meeting_type} — Minutes`, companyName, entityType, meeting, company);

  let y = 38;

  // Meeting Type Header
  y = addMeetingTypeHeader(doc, y, meeting.meeting_type, companyName, meetingDate, isWrittenConsent);
  y = addSectionTitle(doc, y, "Meeting Information");
  y = addLabelValue(doc, y, "Date", meetingDate);
  y = addLabelValue(doc, y, "Type", `${meeting.meeting_type}${meeting.sub_type ? ` — ${meeting.sub_type}` : ""}`);
  if (meeting.meeting_time) y = addLabelValue(doc, y, "Time", meeting.meeting_time);
  if (meeting.meeting_location) y = addLabelValue(doc, y, "Location", meeting.meeting_location);

  // Smart chairperson/secretary paragraph: combine if same person
  const chair = meeting.chairperson?.trim() || "";
  const sec = meeting.mtg_secretary?.trim() || "";
  if (chair && sec && chair.toLowerCase() === sec.toLowerCase()) {
    y = addLabelValue(doc, y, "Chairperson & Secretary", chair);
  } else {
    if (chair) y = addLabelValue(doc, y, "Chairperson", chair);
    if (sec) y = addLabelValue(doc, y, "Secretary", sec);
  }

  if (meeting.tax_year) y = addLabelValue(doc, y, "Tax Year", String(meeting.tax_year));
  if (meeting.others_present) y = addLabelValue(doc, y, "Others Present", meeting.others_present);

  // Section 1244 Stock Plan - include in Organizational Meeting if checked
  if (meeting.meeting_type === "Organizational Meeting" && company?.election_1244) {
    y += 3;
    y = checkPageBreak(doc, y, 60);
    y = addSectionTitle(doc, y, "Section 1244 Stock Plan");
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const section1244Text = `WHEREAS, the Board of Directors deems it to be in the best interest of the corporation and its shareholders to qualify the stock of the corporation as "Section 1244 Stock" as defined in Section 1244 of the Internal Revenue Code of 1986, as amended; and

WHEREAS, the Board of Directors desires to adopt a plan to offer and issue shares of the corporation's common stock pursuant to Section 1244 of the Internal Revenue Code;

NOW, THEREFORE, BE IT RESOLVED, that the corporation hereby adopts the following Section 1244 Stock Plan:

1. The corporation shall offer and issue shares of its common stock for an aggregate dollar amount of consideration that does not exceed the amount authorized by the Articles of Incorporation.

2. Such shares shall be issued only for money, or other property (other than stock or securities), in exchange for the stock.

3. At the time such plan is adopted, the corporation is a "small business corporation" as defined in Section 1244(c)(3) of the Internal Revenue Code.

4. No portion of a prior offering shall be outstanding at the time of the adoption of this plan.

5. The shares issued under this plan shall be designated as "Section 1244 Stock" and the corporation shall maintain such records as are necessary to substantiate compliance with the requirements of Section 1244 of the Internal Revenue Code.

BE IT FURTHER RESOLVED, that the proper officers of the corporation are hereby authorized and directed to take all actions necessary to implement this plan and to maintain the qualification of the stock issued hereunder as Section 1244 Stock.`;
    const lines1244 = doc.splitTextToSize(section1244Text, doc.internal.pageSize.getWidth() - 28);
    doc.text(lines1244, 14, y);
    y += lines1244.length * 3.5 + 6;
  }

  // Directors
  if (data.directors && data.directors.length > 0) {
    y += 3;
    y = checkPageBreak(doc, y, 20 + data.directors.length * 7);
    y = addSectionTitle(doc, y, "Directors Present");
    autoTable(doc, {
      startY: y,
      head: [["Director Name"]],
      body: data.directors.map(d => [d.director_name]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Officers (with salary/bonus)
  if (data.officers && data.officers.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.officers.length * 7);
    y = addSectionTitle(doc, y, "Officers");
    const hasSalaryData = data.officers.some(o => o.salary != null || o.bonus != null);
    autoTable(doc, {
      startY: y,
      head: [hasSalaryData ? ["Title", "Name", "Salary", "Bonus"] : ["Title", "Name"]],
      body: data.officers.map(o => hasSalaryData
        ? [o.title, o.name, o.salary != null ? fmt(o.salary) : "—", o.bonus != null ? fmt(o.bonus) : "—"]
        : [o.title, o.name]
      ),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Shareholders
  if (data.shareholders && data.shareholders.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.shareholders.length * 7);
    y = addSectionTitle(doc, y, entityType === "LLC" ? "Members" : "Shareholders");
    autoTable(doc, {
      startY: y,
      head: [["Name", "Common Shares", "Preferred Shares", "Distribution"]],
      body: data.shareholders.map(s => [
        s.shareholder_name,
        s.common_shares?.toLocaleString() ?? "—",
        s.preferred_shares?.toLocaleString() ?? "—",
        s.distribution || "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Financials
  if (data.financials) {
    const f = data.financials;
    y = checkPageBreak(doc, y, 80);
    y = addSectionTitle(doc, y, "Financial Comparison — Year to Year");

    const yoy = (cur: number | null | undefined, prev: number | null | undefined): string => {
      if (cur == null || prev == null || prev === 0) return "—";
      const change = ((cur - prev) / Math.abs(prev)) * 100;
      return `${change >= 0 ? "▲" : "▼"} ${Math.abs(change).toFixed(1)}%`;
    };

    autoTable(doc, {
      startY: y,
      head: [["", "Current Year", "Previous Year", "YoY Change"]],
      body: [
        ["Total Sales", fmt(f.current_total_sales), fmt(f.previous_total_sales), yoy(f.current_total_sales, f.previous_total_sales)],
        ["Cost of Goods", fmt(f.current_cog), fmt(f.previous_cog), yoy(f.current_cog, f.previous_cog)],
        ["Gross Profit", fmt(f.current_gross_profit), fmt(f.previous_gross_profit), yoy(f.current_gross_profit, f.previous_gross_profit)],
        ["COG Ratio (%)", f.current_cog_ratio != null ? `${Number(f.current_cog_ratio).toFixed(2)}%` : "—", f.previous_cog_ratio != null ? `${Number(f.previous_cog_ratio).toFixed(2)}%` : "—", yoy(f.current_cog_ratio, f.previous_cog_ratio)],
        ["Net Income", fmt(f.current_net_income), fmt(f.previous_net_income), yoy(f.current_net_income, f.previous_net_income)],
      ],
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      columnStyles: { 1: { halign: "right", fontStyle: "bold" }, 2: { halign: "right" }, 3: { halign: "center", fontStyle: "bold" } },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;

    // Draw simple YoY bar chart in PDF
    const pw = doc.internal.pageSize.getWidth();
    const chartW = pw - 28;
    const chartH = 50;
    y = checkPageBreak(doc, y, chartH + 30);
    y = addSectionTitle(doc, y, "Year to Year Visual Comparison");

    const metrics = [
      { label: "Sales", cur: f.current_total_sales, prev: f.previous_total_sales },
      { label: "COG", cur: f.current_cog, prev: f.previous_cog },
      { label: "Gross Profit", cur: f.current_gross_profit, prev: f.previous_gross_profit },
      { label: "Net Income", cur: f.current_net_income, prev: f.previous_net_income },
    ];
    const maxVal = Math.max(...metrics.map(m => Math.max(Math.abs(m.cur || 0), Math.abs(m.prev || 0))), 1);
    const barGroupW = chartW / metrics.length;
    const barW = barGroupW * 0.3;
    const chartX = 14;
    const chartBottom = y + chartH;

    // Background
    doc.setFillColor(248, 249, 250);
    doc.rect(chartX, y, chartW, chartH, "F");
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.2);
    doc.rect(chartX, y, chartW, chartH, "S");

    metrics.forEach((m, i) => {
      const gx = chartX + i * barGroupW + barGroupW * 0.1;
      const curH = (Math.abs(m.cur || 0) / maxVal) * (chartH - 10);
      const prevH = (Math.abs(m.prev || 0) / maxVal) * (chartH - 10);

      // Current year bar (blue)
      doc.setFillColor(45, 55, 120);
      doc.rect(gx, chartBottom - curH, barW, curH, "F");

      // Previous year bar (gray)
      doc.setFillColor(160, 160, 160);
      doc.rect(gx + barW + 2, chartBottom - prevH, barW, prevH, "F");

      // Label
      doc.setFontSize(6);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 60);
      doc.text(m.label, gx + barW, chartBottom + 4, { align: "center" });
    });

    // Legend
    const ly = chartBottom + 8;
    doc.setFillColor(45, 55, 120);
    doc.rect(chartX, ly, 6, 3, "F");
    doc.setFontSize(6);
    doc.setTextColor(60, 60, 60);
    doc.text("Current Year", chartX + 8, ly + 2.5);
    doc.setFillColor(160, 160, 160);
    doc.rect(chartX + 40, ly, 6, 3, "F");
    doc.text("Previous Year", chartX + 48, ly + 2.5);

    y = ly + 10;
  }

  // Counsel
  if (data.counsel && data.counsel.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.counsel.length * 7);
    y = addSectionTitle(doc, y, "Counsel / Banking / Loans");
    autoTable(doc, {
      startY: y,
      head: [["Counsel", "Bank", "Loans"]],
      body: data.counsel.map(c => [c.counsel_name || "—", c.bank_name || "—", c.loans || "—"]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Loans
  if (data.loans && data.loans.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.loans.length * 7);
    y = addSectionTitle(doc, y, "Loans");
    autoTable(doc, {
      startY: y,
      head: [["Type", "Rate", "Amount", "Date", "Notes"]],
      body: data.loans.map(l => [
        l.loan_type || "—",
        l.loan_rate != null ? `${Number(l.loan_rate).toFixed(2)}%` : "—",
        l.loan_amount != null ? fmt(l.loan_amount) : "—",
        l.loan_date ? new Date(l.loan_date + "T00:00:00").toLocaleDateString() : "—",
        l.notes || "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Assets
  if (data.assets && data.assets.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.assets.length * 7);
    y = addSectionTitle(doc, y, "Assets");
    autoTable(doc, {
      startY: y,
      head: [["Type", "Description", "Value"]],
      body: data.assets.map(a => [a.asset_type, a.description, a.value != null ? `$${Number(a.value).toLocaleString(undefined, { minimumFractionDigits: 2 })}` : "—"]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Amendments
  if (data.amendments && data.amendments.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.amendments.length * 12);
    y = addSectionTitle(doc, y, "Amendments");
    data.amendments.forEach((a) => {
      y = checkPageBreak(doc, y, 20);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(a.amendment_type || "Amendment", 14, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const lines = doc.splitTextToSize(a.amendment_text || "", doc.internal.pageSize.getWidth() - 28);
      doc.text(lines, 14, y);
      y += lines.length * 4 + 4;
    });
  }

  // Resolutions
  if (data.resolutions && data.resolutions.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.resolutions.length * 15);
    y = addSectionTitle(doc, y, "Resolutions");
    data.resolutions.forEach((r) => {
      y = checkPageBreak(doc, y, 25);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(r.purpose, 14, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const lines = doc.splitTextToSize(r.resolution_text || "", doc.internal.pageSize.getWidth() - 28);
      doc.text(lines, 14, y);
      y += lines.length * 4 + 4;
    });
  }

  // Auto-generated resolutions from prior year comparison
  if (data.priorYear) {
    const autoResolutions: { purpose: string; text: string }[] = [];
    const entityType = company?.entity_type || "Corporation";
    const isLLC = entityType === "LLC";
    const entityLabel = isLLC ? "LLC" : "corporation";

    // Officer changes: new officers, title changes, salary/bonus changes
    if (data.officers && data.officers.length > 0) {
      const priorOfficers = data.priorYear.officers || [];
      const priorByName: Record<string, any> = {};
      priorOfficers.forEach((o: any) => { priorByName[o.name?.toLowerCase()] = o; });

      data.officers.forEach((o: any) => {
        const prior = priorByName[o.name?.toLowerCase()];
        if (!prior) {
          // New officer
          autoResolutions.push({
            purpose: `Elect ${o.title}`,
            text: `WHEREAS, the ${isLLC ? "members/managers" : "Board of Directors"} has determined it is in the best interests of the ${entityLabel} to elect a new officer, and after discussion, it was\n\nRESOLVED, that ${o.name} is hereby elected as ${o.title} of the ${entityLabel}${o.salary != null ? `, with an annual salary of ${fmt(o.salary)}` : ""}${o.bonus != null ? ` and a bonus of ${fmt(o.bonus)}` : ""}, effective immediately.`,
          });
        } else {
          // Salary change
          if (o.salary != null && prior.salary != null && Number(o.salary) !== Number(prior.salary)) {
            autoResolutions.push({
              purpose: `Adjust ${o.title} Salary`,
              text: `WHEREAS, the ${isLLC ? "members/managers" : "Board of Directors"} has reviewed the compensation of ${o.name}, ${o.title}, and after discussion, it was\n\nRESOLVED, that the annual salary of ${o.name}, ${o.title}, is hereby adjusted from ${fmt(prior.salary)} to ${fmt(o.salary)}, effective immediately.`,
            });
          }
          // Bonus change
          if (o.bonus != null && prior.bonus != null && Number(o.bonus) !== Number(prior.bonus)) {
            autoResolutions.push({
              purpose: `Adjust ${o.title} Bonus`,
              text: `WHEREAS, the ${isLLC ? "members/managers" : "Board of Directors"} has reviewed the bonus compensation of ${o.name}, ${o.title}, and after discussion, it was\n\nRESOLVED, that a bonus of ${fmt(o.bonus)} is hereby authorized for ${o.name}, ${o.title} (prior year bonus: ${fmt(prior.bonus)}).`,
            });
          }
          // Title change
          if (o.title !== prior.title) {
            autoResolutions.push({
              purpose: `Change Officer Title`,
              text: `WHEREAS, ${o.name} previously held the title of ${prior.title}, and the ${isLLC ? "members/managers" : "Board"} has determined a change is appropriate, it was\n\nRESOLVED, that ${o.name} is hereby appointed as ${o.title} of the ${entityLabel}, replacing the prior title of ${prior.title}.`,
            });
          }
        }
      });
    }

    // Benefit changes
    if (data.benefits && data.benefits.length > 0) {
      const priorBenefits = data.priorYear.benefits || [];
      const priorTypes = new Set(priorBenefits.map((b: any) => (b.benefit_type || b.benefit_description || "").toLowerCase()));

      data.benefits.forEach((b: any) => {
        const bType = b.benefit_type || b.benefit_description || "Benefit Plan";
        if (!priorTypes.has(bType.toLowerCase())) {
          autoResolutions.push({
            purpose: `Approve ${bType}`,
            text: `WHEREAS, the ${isLLC ? "members/managers" : "Board of Directors"} has reviewed the proposed ${bType} plan${b.provider ? ` with ${b.provider}` : ""}, and after discussion, it was\n\nRESOLVED, that the ${entityLabel} is hereby authorized to establish the ${bType} plan${b.provider ? ` through ${b.provider}` : ""}${b.retirement_contribution != null ? `, with a contribution of ${fmt(b.retirement_contribution)}` : ""}${b.plan_year ? `, effective for plan year ${b.plan_year}` : ""}.`,
          });
        } else {
          // Check for contribution changes
          const priorMatch = priorBenefits.find((pb: any) => (pb.benefit_type || pb.benefit_description || "").toLowerCase() === bType.toLowerCase());
          if (priorMatch && b.retirement_contribution != null && priorMatch.retirement_contribution != null && Number(b.retirement_contribution) !== Number(priorMatch.retirement_contribution)) {
            autoResolutions.push({
              purpose: `Adjust ${bType} Contribution`,
              text: `WHEREAS, the ${isLLC ? "members/managers" : "Board"} has reviewed the ${bType} plan, and after discussion, it was\n\nRESOLVED, that the contribution to the ${bType} plan is hereby adjusted from ${fmt(priorMatch.retirement_contribution)} to ${fmt(b.retirement_contribution)}.`,
            });
          }
        }
      });
    }

    // Loan changes
    if (data.loans && data.loans.length > 0) {
      const priorLoans = data.priorYear.loans || [];
      const priorLoanTypes = new Set(priorLoans.map((l: any) => `${l.loan_type || ""}|${l.loan_amount || ""}`));

      data.loans.forEach((l: any) => {
        const key = `${l.loan_type || ""}|${l.loan_amount || ""}`;
        if (!priorLoanTypes.has(key)) {
          autoResolutions.push({
            purpose: `Authorize ${l.loan_type || "Loan"}`,
            text: `WHEREAS, the ${isLLC ? "members/managers" : "Board of Directors"} has determined it is in the best interests of the ${entityLabel} to obtain financing, and after discussion, it was\n\nRESOLVED, that the proper ${isLLC ? "managers" : "officers"} are hereby authorized to execute any documents necessary to establish a ${l.loan_type || "loan"}${l.loan_amount != null ? ` in the amount of ${fmt(l.loan_amount)}` : ""}${l.loan_rate != null ? ` at a rate of ${Number(l.loan_rate).toFixed(2)}%` : ""}.`,
          });
        }
      });
    }

    // Authorized signer changes
    if (data.authorizedSigners && data.authorizedSigners.length > 0) {
      const priorSigners = data.priorYear.authorizedSigners || [];
      const priorNames = new Set(priorSigners.map((s: any) => s.signer_name?.toLowerCase()));

      data.authorizedSigners.forEach((s: any) => {
        if (!priorNames.has(s.signer_name?.toLowerCase())) {
          autoResolutions.push({
            purpose: `Authorize Bank Signatory`,
            text: `WHEREAS, the ${isLLC ? "members/managers" : "Board of Directors"} has determined it is necessary to update the authorized signatories, and after discussion, it was\n\nRESOLVED, that ${s.signer_name}${s.title ? `, ${s.title},` : ""} is hereby authorized as a signatory${s.bank_name ? ` on the accounts at ${s.bank_name}` : ""}.`,
          });
        }
      });
    }

    // Print auto-generated resolutions
    if (autoResolutions.length > 0) {
      y += 3;
      y = checkPageBreak(doc, y, 20 + autoResolutions.length * 20);
      y = addSectionTitle(doc, y, "Resolutions — Changes from Prior Year");

      doc.setFontSize(7);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(120, 120, 120);
      doc.text("The following resolutions were auto-generated based on changes from the prior year meeting record.", 14, y);
      y += 5;

      autoResolutions.forEach((r) => {
        y = checkPageBreak(doc, y, 30);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 30, 30);
        doc.text(r.purpose, 14, y);
        y += 4;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        const lines = doc.splitTextToSize(r.text, doc.internal.pageSize.getWidth() - 28);
        doc.text(lines, 14, y);
        y += lines.length * 4 + 4;
      });
    }
  }

  if (data.benefits && data.benefits.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.benefits.length * 7);
    y = addSectionTitle(doc, y, "Benefits");
    autoTable(doc, {
      startY: y,
      head: [["Benefit Type", "Provider", "Agent/Admin", "Plan Year", "Contribution"]],
      body: data.benefits.map(b => [
        b.benefit_type || b.benefit_description || "—",
        b.provider || "—",
        b.agent_administrator || "—",
        b.plan_year?.toString() || "—",
        b.retirement_contribution != null ? fmt(b.retirement_contribution) : "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Agreements
  if (data.agreements && data.agreements.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.agreements.length * 7);
    y = addSectionTitle(doc, y, "Agreements");
    autoTable(doc, {
      startY: y,
      head: [["Type", "Date", "With", "Purpose"]],
      body: data.agreements.map(a => [
        a.agreement_type,
        a.agreement_date ? new Date(a.agreement_date + "T00:00:00").toLocaleDateString() : "—",
        a.agreement_with || "—",
        a.agreement_purpose || "—",
      ]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Other
  if (data.other && data.other.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.other.length * 7);
    y = addSectionTitle(doc, y, "Other Notes");
    autoTable(doc, {
      startY: y,
      head: [["Notes"]],
      body: data.other.map(o => [o.notes]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Authorized Signatories
  if (data.authorizedSigners && data.authorizedSigners.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.authorizedSigners.length * 7);
    y = addSectionTitle(doc, y, "Authorized Signatories");
    autoTable(doc, {
      startY: y,
      head: [["Name", "Title", "Bank"]],
      body: data.authorizedSigners.map(s => [s.signer_name, s.title || "—", s.bank_name || "—"]),
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // Signature block
  y = checkPageBreak(doc, y, 50);
  y += 8;
  doc.setDrawColor(160, 160, 160);
  doc.setLineWidth(0.3);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text("There being no further business, the meeting was adjourned.", 14, y);
  y += 12;

  doc.line(14, y, 90, y);
  doc.text("Secretary", 14, y + 4);
  doc.text("Date: _______________", 95, y + 4);

  y += 14;

  doc.line(14, y, 90, y);
  doc.text("Chairperson", 14, y + 4);
  doc.text("Date: _______________", 95, y + 4);

  addDFIFooter(doc, companyName);
  return doc;
}

// Export individual section PDFs
export function exportSectionPDF(
  sectionTitle: string,
  company: any,
  meeting: any,
  tableHead: string[],
  tableBody: string[][],
) {
  const doc = new jsPDF();
  const companyName = company?.name || "Unknown";
  const entityType = company?.entity_type || "Corporation";
  const meetingDate = new Date(meeting.meeting_date + "T00:00:00").toLocaleDateString();

  addDFIHeader(doc, sectionTitle, companyName, entityType);

  let y = 52;
  y = addLabelValue(doc, y, "Meeting Date", meetingDate);
  y = addLabelValue(doc, y, "Meeting Type", meeting.meeting_type);
  if (meeting.tax_year) y = addLabelValue(doc, y, "Tax Year", String(meeting.tax_year));
  y += 3;

  if (tableBody.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [tableHead],
      body: tableBody,
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      margin: { left: 14, right: 14 },
      styles: { overflow: "linebreak", cellWidth: "auto" },
    });
  } else {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(130, 130, 130);
    doc.text("No records to display.", 14, y + 6);
  }

  addDFIFooter(doc, companyName);
  return doc;
}

export function exportAmendmentsPDF(company: any, meeting: any, amendments: any[]) {
  return exportSectionPDF(
    "Amendments",
    company,
    meeting,
    ["Amendment Type", "Details"],
    amendments.map(a => [a.amendment_type || "—", a.amendment_text || "—"]),
  );
}

export function exportResolutionsPDF(company: any, meeting: any, resolutions: any[]) {
  return exportSectionPDF(
    "Resolutions",
    company,
    meeting,
    ["Purpose", "Resolution Text"],
    resolutions.map(r => [r.purpose, r.resolution_text]),
  );
}

export function exportFinancialsPDF(company: any, meeting: any, financials: any) {
  const doc = new jsPDF();
  const companyName = company?.name || "Unknown";
  const entityType = company?.entity_type || "Corporation";
  const meetingDate = new Date(meeting.meeting_date + "T00:00:00").toLocaleDateString();

  addDFIHeader(doc, "Financial Comparison", companyName, entityType);

  let y = 52;
  y = addLabelValue(doc, y, "Meeting Date", meetingDate);
  if (meeting.tax_year) y = addLabelValue(doc, y, "Tax Year", String(meeting.tax_year));
  y += 3;

  if (financials) {
    // YoY helper
    const yoy = (cur: any, prev: any): string => {
      if (cur == null || prev == null || prev === 0) return "";
      const pct = ((Number(cur) - Number(prev)) / Math.abs(Number(prev))) * 100;
      return `${pct >= 0 ? "▲" : "▼"} ${Math.abs(pct).toFixed(1)}%`;
    };

    autoTable(doc, {
      startY: y,
      head: [["", "Current Year", "Previous Year", "YoY Change"]],
      body: [
        ["Total Sales", fmt(financials.current_total_sales), fmt(financials.previous_total_sales), yoy(financials.current_total_sales, financials.previous_total_sales)],
        ["Cost of Goods", fmt(financials.current_cog), fmt(financials.previous_cog), yoy(financials.current_cog, financials.previous_cog)],
        ["Gross Profit", fmt(financials.current_gross_profit), fmt(financials.previous_gross_profit), yoy(financials.current_gross_profit, financials.previous_gross_profit)],
        ["COG Ratio (%)", financials.current_cog_ratio != null ? `${Number(financials.current_cog_ratio).toFixed(2)}%` : "—", financials.previous_cog_ratio != null ? `${Number(financials.previous_cog_ratio).toFixed(2)}%` : "—", yoy(financials.current_cog_ratio, financials.previous_cog_ratio)],
        ["Net Income", fmt(financials.current_net_income), fmt(financials.previous_net_income), yoy(financials.current_net_income, financials.previous_net_income)],
      ],
      theme: "grid",
      headStyles: { fillColor: [45, 55, 72], fontSize: 8, fontStyle: "bold" },
      bodyStyles: { fontSize: 8 },
      columnStyles: { 1: { halign: "right", fontStyle: "bold" }, 2: { halign: "right" }, 3: { halign: "center", fontSize: 7 } },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 8;

    // Draw simple bar chart comparison
    const pw = doc.internal.pageSize.getWidth();
    y = checkPageBreak(doc, y, 90);
    y = addSectionTitle(doc, y, "Visual Comparison");

    const chartItems = [
      { label: "Total Sales", cur: Number(financials.current_total_sales) || 0, prev: Number(financials.previous_total_sales) || 0 },
      { label: "Gross Profit", cur: Number(financials.current_gross_profit) || 0, prev: Number(financials.previous_gross_profit) || 0 },
      { label: "COG", cur: Number(financials.current_cog) || 0, prev: Number(financials.previous_cog) || 0 },
      { label: "Net Income", cur: Number(financials.current_net_income) || 0, prev: Number(financials.previous_net_income) || 0 },
    ];

    const maxVal = Math.max(...chartItems.map(i => Math.max(Math.abs(i.cur), Math.abs(i.prev))), 1);
    const barMaxWidth = pw - 80;
    const barHeight = 6;
    const groupHeight = 22;

    // Legend
    doc.setFillColor(45, 55, 120);
    doc.rect(14, y, 8, 4, "F");
    doc.setFontSize(7);
    doc.setTextColor(80, 80, 80);
    doc.text("Current Year", 24, y + 3);
    doc.setFillColor(160, 160, 180);
    doc.rect(60, y, 8, 4, "F");
    doc.text("Previous Year", 70, y + 3);
    y += 10;

    chartItems.forEach((item) => {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 60);
      doc.text(item.label, 14, y + 3);

      const curWidth = maxVal > 0 ? (Math.abs(item.cur) / maxVal) * barMaxWidth : 0;
      const prevWidth = maxVal > 0 ? (Math.abs(item.prev) / maxVal) * barMaxWidth : 0;

      doc.setFillColor(45, 55, 120);
      doc.roundedRect(50, y - 2, Math.max(curWidth, 1), barHeight, 1, 1, "F");

      doc.setFillColor(160, 160, 180);
      doc.roundedRect(50, y + barHeight, Math.max(prevWidth, 1), barHeight, 1, 1, "F");

      // Values
      doc.setFontSize(6);
      doc.setTextColor(30, 30, 30);
      if (item.cur > 0) doc.text(fmt(item.cur), 50 + curWidth + 2, y + 3);
      if (item.prev > 0) doc.text(fmt(item.prev), 50 + prevWidth + 2, y + barHeight + 5);

      y += groupHeight;
    });
  }

  addDFIFooter(doc, companyName);
  return doc;
}

function fmt(val: any): string {
  if (val == null) return "—";
  return `$${Number(val).toLocaleString(undefined, { minimumFractionDigits: 2 })}`;
}

// Save and download
export function downloadPDF(doc: jsPDF, fileName: string) {
  doc.save(fileName);
}

// Get PDF as blob URL for preview
export function getPDFPreviewUrl(doc: jsPDF): string {
  const blob = doc.output("blob");
  return URL.createObjectURL(blob);
}
