/**
 * Shared resolution types with action category groupings.
 * Used by MeetingResolutions.tsx and WrittenConsentWizard.tsx.
 */

export interface ResolutionType {
  label: string;
  statute?: string;
  template?: string;
  category?: string;
}

export const ACTION_CATEGORIES = [
  "Banking",
  "Compensation",
  "Governance",
  "Operations",
  "Ownership",
  "Tax Elections",
  "Benefits",
  "Other",
] as const;

export type ActionCategory = (typeof ACTION_CATEGORIES)[number];

// Maps resolution labels to categories
const CATEGORY_MAP: Record<string, ActionCategory> = {
  "Authorize a Line of Credit": "Banking",
  "Approve Officer Bonuses": "Compensation",
  "Approve Officer Bonuses (Reasonable Compensation)": "Compensation",
  "Approve Annual Officer Compensation": "Compensation",
  "Approve Guaranteed Payments": "Compensation",
  "Approve Reasonable Compensation": "Compensation",
  "Approve Issuance of Shares": "Ownership",
  "Approve Transfer/Sale of Shares": "Ownership",
  "Approve Transfer of Membership Interest": "Ownership",
  "Admit New Member": "Ownership",
  "Approve Distributions/Dividends": "Compensation",
  "Approve Distributions": "Compensation",
  "Approve Member Distributions": "Compensation",
  "Elect Officers": "Governance",
  "Elect Directors": "Governance",
  "Elect Directors/Board Members": "Governance",
  "Re-elect Board of Directors": "Governance",
  "Elect/Appoint Managers": "Governance",
  "Re-elect Managers": "Governance",
  "Adopt Regular Meeting Resolution": "Governance",
  "Name Directors to Committees": "Governance",
  "Approve Employment Agreement": "Operations",
  "Approve Employment/Service Agreement": "Operations",
  "Approve Lease Agreement": "Operations",
  "Approve Purchase/Sale of Assets": "Operations",
  "Ratify Prior Actions": "Operations",
  "Approve Tax Election (S-Corp)": "Tax Elections",
  "Approve Tax Classification Election": "Tax Elections",
  "Revoke S-Election": "Tax Elections",
  "Approve Employee Benefit Plan": "Benefits",
  "Approve Amendments to Articles of Incorporation": "Governance",
  "Approve Amendments to Bylaws": "Governance",
  "Approve Amendments to Operating Agreement": "Governance",
  "Approve Amendments to Partnership Agreement": "Governance",
  "Approve Merger or Consolidation": "Governance",
  "Approve Dissolution": "Governance",
  "Approve Authorized Binders": "Governance",
  "Approve Budget": "Operations",
  "Approve Grant Application": "Operations",
  "Approve Fundraising Activity": "Operations",
  "Approve Conflict of Interest Policy": "Governance",
  "Approve Charitable Purpose Activity": "Operations",
  "Approve Partner Distributions": "Compensation",
  "Admit New Partner": "Ownership",
  "Approve Transfer of Partnership Interest": "Ownership",
  "Approve Loan from Related Party": "Banking",
  "Approve Loan to Related Party": "Banking",
  "Approve Related Party Loan Agreement": "Banking",
  "Other": "Other",
};

export function getResolutionCategory(label: string): ActionCategory {
  return CATEGORY_MAP[label] || "Other";
}

export function filterByCategory(
  resolutions: ResolutionType[],
  category: ActionCategory
): ResolutionType[] {
  return resolutions.filter(
    (r) => getResolutionCategory(r.label) === category
  );
}

export const RESOLUTION_TYPES: Record<string, ResolutionType[]> = {
  Corporation: [
    { label: "Authorize a Line of Credit", statute: "Wis. Stat. § 180.0302", template: "WHEREAS, it would be in the best interests of the corporation to obtain a line of credit, and after discussion, it was\n\nRESOLVED, that the proper officers of this corporation are hereby authorized to contact the Bank and are further authorized to execute any documents necessary to establish a line of credit not to exceed $_______ (amount) dollars for and on behalf of the corporation." },
    { label: "Approve Officer Bonuses", statute: "Wis. Stat. § 180.0302", template: "WHEREAS, the Board of Directors has reviewed the performance of the officers of the corporation and, after discussion, it was\n\nRESOLVED, that bonuses be paid to the following officers in the amounts set forth below:\n\n[Officer Name] - $[Amount]" },
    { label: "Approve Annual Officer Compensation", statute: "Wis. Stat. § 180.0302; Wis. Stat. § 180.0840", template: "WHEREAS, the shareholders have reviewed the compensation of the officers of the corporation for the fiscal year ending ______, and\n\nWHEREAS, the shareholders have considered the duties, responsibilities, and performance of each officer, and have determined that the following compensation is fair and reasonable,\n\nRESOLVED, that the annual compensation for the officers of the corporation shall be as follows, effective ______:\n\nPresident: $______\nVice President: $______\nSecretary: $______\nTreasurer: $______\n\nFURTHER RESOLVED, that said compensation shall include salary and any benefits as determined by the Board of Directors, and the proper officers are authorized to execute any documents necessary to implement this resolution." },
    { label: "Approve Issuance of Shares", statute: "Wis. Stat. § 180.0621", template: "RESOLVED, that the corporation is hereby authorized to issue ______ shares of ______ stock to ______ in consideration of $______ per share." },
    { label: "Approve Transfer/Sale of Shares", statute: "Wis. Stat. § 180.0621", template: "RESOLVED, that the transfer of ______ shares of ______ stock from ______ to ______ is hereby approved and the officers are directed to update the stock ledger accordingly." },
    { label: "Adopt Regular Meeting Resolution", statute: "Wis. Stat. § 180.0820", template: "RESOLVED, that regular meetings of the Board of Directors shall be held on the ______ day of each ______ at ______ o'clock at the principal office of the corporation, or at such other place as may be designated by the Chairman." },
    { label: "Approve Distributions/Dividends", statute: "Wis. Stat. § 180.0640", template: "RESOLVED, that a dividend of $______ per share be declared on the outstanding ______ stock of the corporation, payable on ______ to shareholders of record as of ______." },
    { label: "Elect Officers", statute: "Wis. Stat. § 180.0840", template: "RESOLVED, that the following persons are hereby elected to the offices set forth opposite their names, to serve until their successors are duly elected and qualified:\n\nPresident: ______\nVice President: ______\nSecretary: ______\nTreasurer: ______" },
    { label: "Elect Directors", statute: "Wis. Stat. § 180.0803", template: "RESOLVED, that the following persons are hereby elected as directors of the corporation, to serve until the next annual meeting or until their successors are duly elected and qualified:\n\n______" },
    { label: "Re-elect Board of Directors", statute: "Wis. Stat. § 180.0803", template: "WHEREAS, the terms of the current members of the Board of Directors expire at this annual meeting of shareholders, and\n\nWHEREAS, the shareholders have reviewed the qualifications and service of the current directors,\n\nRESOLVED, that the following persons are hereby re-elected as directors of the corporation, each to serve until the next annual meeting of shareholders or until their successors are duly elected and qualified:\n\n______\n______\n______" },
    { label: "Name Directors to Committees", statute: "Wis. Stat. § 180.0825", template: "RESOLVED, that the following directors are hereby appointed to serve on the ______ Committee:\n\n______" },
    { label: "Approve Employment Agreement", statute: "Wis. Stat. § 180.0302", template: "RESOLVED, that the corporation is hereby authorized to enter into an employment agreement with ______ on the terms presented to and reviewed by the Board." },
    { label: "Approve Lease Agreement", statute: "Wis. Stat. § 180.0302", template: "RESOLVED, that the proper officers are hereby authorized to execute a lease agreement for the premises located at ______ on the terms presented to the Board." },
    { label: "Approve Purchase/Sale of Assets", statute: "Wis. Stat. § 180.1202", template: "RESOLVED, that the corporation is hereby authorized to [purchase/sell] the following assets: ______ for consideration of $______." },
    { label: "Ratify Prior Actions", statute: "Wis. Stat. § 180.0302", template: "RESOLVED, that all acts and transactions of the officers and directors of the corporation since the last meeting of the Board are hereby ratified and approved." },
    { label: "Approve Tax Election (S-Corp)", statute: "IRC § 1362", template: "RESOLVED, that the corporation hereby elects to be treated as an S corporation under IRC § 1362, and the proper officers are authorized to file IRS Form 2553." },
    { label: "Approve Employee Benefit Plan", statute: "Wis. Stat. § 180.0302", template: "RESOLVED, that the corporation is authorized to establish and maintain the following employee benefit plan: ______" },
    { label: "Approve Amendments to Articles of Incorporation", statute: "Wis. Stat. § 180.1003", template: "WHEREAS, the shareholders have reviewed the proposed amendment(s) to the Articles of Incorporation, and after discussion, it was\n\nRESOLVED, that Article ______ of the Articles of Incorporation is hereby amended to read as follows:\n\n______\n\nFURTHER RESOLVED, that the proper officers are directed to file the Articles of Amendment with the Wisconsin Department of Financial Institutions." },
    { label: "Approve Amendments to Bylaws", statute: "Wis. Stat. § 180.1020", template: "RESOLVED, that the Bylaws of the corporation are hereby amended as follows:\n\n______\n\nThe Secretary is directed to update the corporate records to reflect this amendment." },
    { label: "Approve Merger or Consolidation", statute: "Wis. Stat. § 180.1103", template: "WHEREAS, the Board of Directors has recommended the merger of the corporation with ______, and\n\nWHEREAS, the shareholders have reviewed the Plan of Merger,\n\nRESOLVED, that the Plan of Merger between this corporation and ______ is hereby approved, and the proper officers are authorized to execute all documents necessary to effectuate the merger." },
    { label: "Approve Dissolution", statute: "Wis. Stat. § 180.1402", template: "WHEREAS, the shareholders have determined it is in the best interests of the corporation to dissolve, and after discussion, it was\n\nRESOLVED, that the corporation is hereby authorized to dissolve and wind up its affairs in accordance with Wisconsin Statutes Chapter 180, and the proper officers are directed to file Articles of Dissolution with the Wisconsin DFI." },
    { label: "Other" },
  ],
  "S-Corp": [
    { label: "Authorize a Line of Credit", statute: "Wis. Stat. § 180.0302", template: "WHEREAS, it would be in the best interests of the corporation to obtain a line of credit, and after discussion, it was\n\nRESOLVED, that the proper officers of this corporation are hereby authorized to contact the Bank and are further authorized to execute any documents necessary to establish a line of credit not to exceed $_______ (amount) dollars for and on behalf of the corporation." },
    { label: "Approve Officer Bonuses (Reasonable Compensation)", statute: "Wis. Stat. § 180.0302; IRC § 1366", template: "WHEREAS, the Board has reviewed officer compensation in light of IRS reasonable compensation requirements for S corporations, and after discussion, it was\n\nRESOLVED, that bonuses be paid to the following officers:\n\n[Officer Name] - $[Amount]\n\nThe Board has determined these amounts constitute reasonable compensation for services rendered." },
    { label: "Approve Annual Officer Compensation", statute: "Wis. Stat. § 180.0302; IRC § 1366; Wis. Stat. § 180.0840", template: "WHEREAS, the shareholders have reviewed the compensation of the officers of the corporation for the fiscal year ending ______, and\n\nWHEREAS, the shareholders have considered the duties, responsibilities, and performance of each officer, and have determined that the following compensation constitutes reasonable compensation as required under IRC § 1366 for S corporation officer-shareholders,\n\nRESOLVED, that the annual compensation for the officers of the corporation shall be as follows, effective ______:\n\nPresident: $______\nVice President: $______\nSecretary: $______\nTreasurer: $______\n\nFURTHER RESOLVED, that the Board of Directors has determined the above amounts represent reasonable compensation for the services actually rendered by each officer, taking into account comparable salaries in similar businesses, the officer's qualifications, and the nature and scope of their duties.\n\nFURTHER RESOLVED, that the proper officers are authorized to execute any documents necessary to implement this resolution." },
    { label: "Approve Issuance of Shares", statute: "Wis. Stat. § 180.0621; IRC § 1361(b)", template: "RESOLVED, that the corporation is authorized to issue ______ shares of common stock to ______, provided that the issuance does not cause the corporation to exceed 100 shareholders or create a second class of stock in violation of IRC § 1361(b)." },
    { label: "Approve Transfer/Sale of Shares", statute: "Wis. Stat. § 180.0621; IRC § 1361(b)", template: "RESOLVED, that the transfer of ______ shares from ______ to ______ is approved, subject to verification that the transferee is an eligible S corporation shareholder under IRC § 1361(b)(1)." },
    { label: "Adopt Regular Meeting Resolution", statute: "Wis. Stat. § 180.0820", template: "RESOLVED, that regular meetings of the Board of Directors shall be held on the ______ day of each ______ at ______ o'clock at the principal office of the corporation." },
    { label: "Approve Distributions", statute: "Wis. Stat. § 180.0640; IRC § 1368", template: "RESOLVED, that a distribution of $______ per share be made to shareholders, to be treated in accordance with IRC § 1368 (distributions from AAA, then AE&P if applicable)." },
    { label: "Elect Officers", statute: "Wis. Stat. § 180.0840", template: "RESOLVED, that the following persons are hereby elected to the offices set forth opposite their names:\n\nPresident: ______\nVice President: ______\nSecretary: ______\nTreasurer: ______" },
    { label: "Elect Directors", statute: "Wis. Stat. § 180.0803", template: "RESOLVED, that the following persons are hereby elected as directors:\n\n______" },
    { label: "Re-elect Board of Directors", statute: "Wis. Stat. § 180.0803", template: "WHEREAS, the terms of the current members of the Board of Directors expire at this annual meeting of shareholders, and\n\nWHEREAS, the shareholders have reviewed the qualifications and service of the current directors,\n\nRESOLVED, that the following persons are hereby re-elected as directors of the corporation, each to serve until the next annual meeting of shareholders or until their successors are duly elected and qualified:\n\n______\n______\n______" },
    { label: "Approve Employment Agreement", statute: "Wis. Stat. § 180.0302", template: "RESOLVED, that the corporation is authorized to enter into an employment agreement with ______ on the terms reviewed by the Board." },
    { label: "Approve Lease Agreement", statute: "Wis. Stat. § 180.0302", template: "RESOLVED, that the proper officers are authorized to execute a lease agreement for premises at ______." },
    { label: "Approve Purchase/Sale of Assets", statute: "Wis. Stat. § 180.1202", template: "RESOLVED, that the corporation is authorized to [purchase/sell] the following assets: ______ for $______." },
    { label: "Ratify Prior Actions", statute: "Wis. Stat. § 180.0302", template: "RESOLVED, that all acts and transactions of the officers and directors since the last meeting are hereby ratified and approved." },
    { label: "Revoke S-Election", statute: "IRC § 1362(d)", template: "RESOLVED, that the corporation hereby revokes its election to be treated as an S corporation, effective ______, and the proper officers are authorized to file the necessary documents with the IRS." },
    { label: "Approve Employee Benefit Plan", statute: "Wis. Stat. § 180.0302; IRC § 1372", template: "RESOLVED, that the corporation is authorized to establish the following employee benefit plan: ______\n\nNote: Under IRC § 1372, 2% shareholders are treated as partners for fringe benefit purposes." },
    { label: "Approve Amendments to Articles of Incorporation", statute: "Wis. Stat. § 180.1003", template: "WHEREAS, the shareholders have reviewed the proposed amendment(s) to the Articles of Incorporation, and after discussion, it was\n\nRESOLVED, that Article ______ of the Articles of Incorporation is hereby amended to read as follows:\n\n______\n\nFURTHER RESOLVED, that the proper officers are directed to file the Articles of Amendment with the Wisconsin DFI." },
    { label: "Approve Dissolution", statute: "Wis. Stat. § 180.1402", template: "WHEREAS, the shareholders have determined it is in the best interests of the corporation to dissolve, and after discussion, it was\n\nRESOLVED, that the corporation is hereby authorized to dissolve in accordance with Wisconsin Statutes Chapter 180." },
    { label: "Other" },
  ],
  "Single Member LLC": [
    { label: "Authorize a Line of Credit", statute: "Wis. Stat. § 183.0301", template: "WHEREAS, it would be in the best interests of the LLC to obtain a line of credit, and after discussion, it was\n\nRESOLVED, that the [managers/members] are authorized to execute documents to establish a line of credit not to exceed $_______ for the LLC." },
    { label: "Approve Member Distributions", statute: "Wis. Stat. § 183.0504", template: "RESOLVED, that a distribution of $______ be made to the members in accordance with their respective membership interests as set forth in the Operating Agreement." },
    { label: "Approve Guaranteed Payments", statute: "IRC § 707(c)", template: "RESOLVED, that guaranteed payments in the following amounts be made to the following members for services rendered:\n\n[Member Name] - $[Amount]" },
    { label: "Approve Employment/Service Agreement", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to enter into a service agreement with ______ on the terms reviewed by the [members/managers]." },
    { label: "Approve Lease Agreement", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to execute a lease for premises at ______." },
    { label: "Approve Purchase/Sale of Assets", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to [purchase/sell] the following assets: ______ for $______." },
    { label: "Approve Tax Classification Election", statute: "IRC § 301.7701-3", template: "RESOLVED, that the LLC hereby elects to be classified as a ______ for federal tax purposes, and the proper representatives are authorized to file IRS Form 8832." },
    { label: "Ratify Prior Actions", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that all acts and transactions of the [managers/members] since the last meeting are hereby ratified and approved." },
    { label: "Approve Employee Benefit Plan", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to establish the following employee benefit plan: ______" },
    { label: "Approve Amendments to Operating Agreement", statute: "Wis. Stat. § 183.0103", template: "RESOLVED, that the Operating Agreement of the LLC is hereby amended as follows:\n\n______\n\nThe [Manager/Members] are directed to update the records accordingly." },
    { label: "Approve Dissolution", statute: "Wis. Stat. § 183.0901", template: "WHEREAS, the members have determined it is in the best interests of the LLC to dissolve, and after discussion, it was\n\nRESOLVED, that the LLC is hereby authorized to dissolve and wind up its affairs in accordance with the Operating Agreement and Wisconsin Statutes Chapter 183." },
    { label: "Other" },
  ],
  LLC: [
    { label: "Authorize a Line of Credit", statute: "Wis. Stat. § 183.0301", template: "WHEREAS, it would be in the best interests of the LLC to obtain a line of credit, and after discussion, it was\n\nRESOLVED, that the [managers/members] are authorized to execute documents to establish a line of credit not to exceed $_______ for the LLC." },
    { label: "Approve Member Distributions", statute: "Wis. Stat. § 183.0504", template: "RESOLVED, that a distribution of $______ be made to the members in accordance with their respective membership interests as set forth in the Operating Agreement." },
    { label: "Approve Guaranteed Payments", statute: "IRC § 707(c)", template: "RESOLVED, that guaranteed payments in the following amounts be made to the following members for services rendered:\n\n[Member Name] - $[Amount]" },
    { label: "Admit New Member", statute: "Wis. Stat. § 183.0801", template: "RESOLVED, that ______ is hereby admitted as a member of the LLC with a ______% membership interest, effective ______, in accordance with the Operating Agreement." },
    { label: "Approve Transfer of Membership Interest", statute: "Wis. Stat. § 183.0706", template: "RESOLVED, that the transfer of ______% membership interest from ______ to ______ is hereby approved, subject to the terms of the Operating Agreement." },
    { label: "Elect/Appoint Managers", statute: "Wis. Stat. § 183.0401", template: "RESOLVED, that the following persons are appointed as managers of the LLC:\n\n______" },
    { label: "Re-elect Managers", statute: "Wis. Stat. § 183.0401", template: "WHEREAS, the terms of the current managers of the LLC expire at this annual meeting, and\n\nWHEREAS, the members have reviewed the qualifications and service of the current managers,\n\nRESOLVED, that the following persons are hereby re-appointed as managers of the LLC, each to serve until the next annual meeting of members or until their successors are duly appointed:\n\n______" },
    { label: "Approve Employment/Service Agreement", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to enter into a service agreement with ______ on the terms reviewed by the [members/managers]." },
    { label: "Approve Lease Agreement", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to execute a lease for premises at ______." },
    { label: "Approve Purchase/Sale of Assets", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to [purchase/sell] the following assets: ______ for $______." },
    { label: "Approve Tax Classification Election", statute: "IRC § 301.7701-3", template: "RESOLVED, that the LLC hereby elects to be classified as a ______ for federal tax purposes, and the proper representatives are authorized to file IRS Form 8832." },
    { label: "Ratify Prior Actions", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that all acts and transactions of the [managers/members] since the last meeting are hereby ratified and approved." },
    { label: "Approve Employee Benefit Plan", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to establish the following employee benefit plan: ______" },
    { label: "Adopt Regular Meeting Resolution", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that regular meetings of the [members/managers] shall be held on the ______ day of each ______ at ______ o'clock." },
    { label: "Approve Amendments to Operating Agreement", statute: "Wis. Stat. § 183.0103", template: "RESOLVED, that the Operating Agreement of the LLC is hereby amended as follows:\n\n______\n\nThe [Manager/Members] are directed to update the records accordingly." },
    { label: "Approve Dissolution", statute: "Wis. Stat. § 183.0901", template: "WHEREAS, the members have determined it is in the best interests of the LLC to dissolve, and after discussion, it was\n\nRESOLVED, that the LLC is hereby authorized to dissolve and wind up its affairs in accordance with the Operating Agreement and Wisconsin Statutes Chapter 183." },
    { label: "Approve Authorized Binders", statute: "Wis. Stat. § 183.0302; Wis. Stat. § 183.0303", template: "WHEREAS, the members of this company deem it in the best interest of the company to clarify and designate specific authority for individuals to act on behalf of the company:\n\nNOW, THEREFORE, BE IT RESOLVED, that the following person(s) is/are hereby granted authority to bind the company, including entering into contracts, executing documents, managing bank accounts, and taking any action necessary in the ordinary course of business:\n\n______\n______\n\nRESOLVED FURTHER, that when appropriate to clarify the authority of specific individuals to act on behalf of the company, a Statement of Authority or Statement of Denial shall be filed with the WI Secretary of State in accordance with Wisconsin Statutes § 183.0302 and § 183.0303 of The Uniform Limited Liability Company Law.\n\nRESOLVED FURTHER, that this authority shall remain in effect until revoked by a subsequent resolution of the members of the company." },
    { label: "Other" },
  ],
  "LLC-S": [
    { label: "Authorize a Line of Credit", statute: "Wis. Stat. § 183.0301", template: "WHEREAS, it would be in the best interests of the LLC to obtain a line of credit, and after discussion, it was\n\nRESOLVED, that the [managers/members] are authorized to execute documents to establish a line of credit not to exceed $_______ for the LLC." },
    { label: "Approve Member Distributions", statute: "Wis. Stat. § 183.0504 / IRC § 1368", template: "RESOLVED, that a distribution of $______ be made to the members in accordance with their respective membership interests, to be treated in accordance with IRC § 1368." },
    { label: "Approve Reasonable Compensation", statute: "Wis. Stat. § 183.0301; IRC § 1366", template: "WHEREAS, the members have reviewed compensation in light of IRS reasonable compensation requirements for S corporations, and after discussion, it was\n\nRESOLVED, that compensation be paid to the following member-employees:\n\n[Member Name] - $[Amount]\n\nThe members have determined these amounts constitute reasonable compensation for services rendered." },
    { label: "Admit New Member", statute: "Wis. Stat. § 183.0801 / IRC § 1361(b)", template: "RESOLVED, that ______ is hereby admitted as a member of the LLC with a ______% membership interest, effective ______, subject to verification that the new member is an eligible S corporation shareholder under IRC § 1361(b)(1)." },
    { label: "Approve Transfer of Membership Interest", statute: "Wis. Stat. § 183.0706 / IRC § 1361(b)", template: "RESOLVED, that the transfer of ______% membership interest from ______ to ______ is hereby approved, subject to the terms of the Operating Agreement and verification of S corporation eligibility under IRC § 1361(b)(1)." },
    { label: "Elect/Appoint Managers", statute: "Wis. Stat. § 183.0401", template: "RESOLVED, that the following persons are appointed as managers of the LLC:\n\n______" },
    { label: "Re-elect Managers", statute: "Wis. Stat. § 183.0401", template: "WHEREAS, the terms of the current managers of the LLC expire at this annual meeting, and\n\nWHEREAS, the members have reviewed the qualifications and service of the current managers,\n\nRESOLVED, that the following persons are hereby re-appointed as managers of the LLC, each to serve until the next annual meeting of members or until their successors are duly appointed:\n\n______" },
    { label: "Approve Employment/Service Agreement", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to enter into a service agreement with ______ on the terms reviewed by the [members/managers]." },
    { label: "Approve Lease Agreement", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to execute a lease for premises at ______." },
    { label: "Approve Purchase/Sale of Assets", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that the LLC is authorized to [purchase/sell] the following assets: ______ for $______." },
    { label: "Revoke S-Election", statute: "IRC § 1362(d)", template: "RESOLVED, that the LLC hereby revokes its election to be treated as an S corporation, effective ______, and the proper representatives are authorized to file the necessary documents with the IRS." },
    { label: "Approve Employee Benefit Plan", statute: "Wis. Stat. § 183.0301; IRC § 1372", template: "RESOLVED, that the LLC is authorized to establish the following employee benefit plan: ______\n\nNote: Under IRC § 1372, 2% shareholder-members are treated as partners for fringe benefit purposes." },
    { label: "Ratify Prior Actions", statute: "Wis. Stat. § 183.0301", template: "RESOLVED, that all acts and transactions of the [managers/members] since the last meeting are hereby ratified and approved." },
    { label: "Approve Amendments to Operating Agreement", statute: "Wis. Stat. § 183.0103", template: "RESOLVED, that the Operating Agreement of the LLC is hereby amended as follows:\n\n______\n\nThe [Manager/Members] are directed to update the records accordingly." },
    { label: "Approve Authorized Binders", statute: "Wis. Stat. § 183.0302; Wis. Stat. § 183.0303", template: "WHEREAS, the members of this company deem it in the best interest of the company to clarify and designate specific authority for individuals to act on behalf of the company:\n\nNOW, THEREFORE, BE IT RESOLVED, that the following person(s) is/are hereby granted authority to bind the company, including entering into contracts, executing documents, managing bank accounts, and taking any action necessary in the ordinary course of business:\n\n______\n______\n\nRESOLVED FURTHER, that this authority shall remain in effect until revoked by a subsequent resolution of the members of the company." },
    { label: "Approve Dissolution", statute: "Wis. Stat. § 183.0901", template: "WHEREAS, the members have determined it is in the best interests of the LLC to dissolve, and after discussion, it was\n\nRESOLVED, that the LLC is hereby authorized to dissolve and wind up its affairs in accordance with the Operating Agreement and Wisconsin Statutes Chapter 183." },
    { label: "Other" },
  ],
  "Non-Profit": [
    { label: "Authorize a Line of Credit", statute: "Wis. Stat. § 181.0302", template: "WHEREAS, it would be in the best interests of the corporation to obtain a line of credit, and after discussion, it was\n\nRESOLVED, that the proper officers are authorized to establish a line of credit not to exceed $_______ for the corporation." },
    { label: "Approve Budget", statute: "Wis. Stat. § 181.0302", template: "RESOLVED, that the proposed budget for fiscal year ______ in the total amount of $______ is hereby adopted." },
    { label: "Elect Officers", statute: "Wis. Stat. § 181.0840", template: "RESOLVED, that the following persons are elected to the offices indicated:\n\nPresident: ______\nVice President: ______\nSecretary: ______\nTreasurer: ______" },
    { label: "Elect Directors/Board Members", statute: "Wis. Stat. § 181.0803", template: "RESOLVED, that the following persons are elected as directors, to serve until the next annual meeting:\n\n______" },
    { label: "Re-elect Board of Directors", statute: "Wis. Stat. § 181.0803", template: "WHEREAS, the terms of the current members of the Board of Directors expire at this annual meeting, and\n\nWHEREAS, the members/delegates have reviewed the qualifications and service of the current directors,\n\nRESOLVED, that the following persons are hereby re-elected as directors of the corporation, each to serve until the next annual meeting or until their successors are duly elected and qualified:\n\n______" },
    { label: "Approve Grant Application", statute: "Wis. Stat. § 181.0302", template: "RESOLVED, that the corporation is authorized to apply for a grant from ______ in the amount of $______ for the purpose of ______." },
    { label: "Approve Fundraising Activity", statute: "Wis. Stat. § 181.0302", template: "RESOLVED, that the corporation is authorized to conduct a ______ fundraising event on ______ at ______." },
    { label: "Approve Conflict of Interest Policy", statute: "IRC § 501(c)(3); Wis. Stat. § 181.0831", template: "RESOLVED, that the Conflict of Interest Policy as presented is hereby adopted, and all directors and officers shall complete annual disclosure statements." },
    { label: "Approve Lease Agreement", statute: "Wis. Stat. § 181.0302", template: "RESOLVED, that the proper officers are authorized to execute a lease for premises at ______." },
    { label: "Approve Purchase/Sale of Assets", statute: "Wis. Stat. § 181.1202", template: "RESOLVED, that the corporation is authorized to [purchase/sell]: ______ for $______." },
    { label: "Ratify Prior Actions", statute: "Wis. Stat. § 181.0302", template: "RESOLVED, that all acts and transactions of the officers and directors since the last meeting are hereby ratified and approved." },
    { label: "Adopt Regular Meeting Resolution", statute: "Wis. Stat. § 181.0820", template: "RESOLVED, that regular meetings of the Board shall be held on the ______ day of each ______ at ______ o'clock." },
    { label: "Approve Charitable Purpose Activity", statute: "IRC § 501(c)(3)", template: "RESOLVED, that the corporation is authorized to undertake the following charitable activity: ______" },
    { label: "Approve Amendments to Articles of Incorporation", statute: "Wis. Stat. § 181.1003", template: "RESOLVED, that the Articles of Incorporation are hereby amended as follows:\n\n______\n\nThe proper officers are directed to file the Articles of Amendment with the Wisconsin DFI." },
    { label: "Approve Dissolution", statute: "Wis. Stat. § 181.1402", template: "WHEREAS, the members/directors have determined it is in the best interests of the corporation to dissolve,\n\nRESOLVED, that the corporation is hereby authorized to dissolve in accordance with Wisconsin Statutes Chapter 181 and to distribute remaining assets to qualified charitable organizations." },
    { label: "Other" },
  ],
  Partnership: [
    { label: "Authorize a Line of Credit", template: "WHEREAS, it would be in the best interests of the partnership to obtain a line of credit, and after discussion, it was\n\nRESOLVED, that the [managing partner/general partners] are authorized to establish a line of credit not to exceed $_______." },
    { label: "Approve Partner Distributions", template: "RESOLVED, that distributions be made to the partners in accordance with their partnership interests as follows:\n\n[Partner Name] - $[Amount]" },
    { label: "Approve Guaranteed Payments", statute: "IRC § 707(c)", template: "RESOLVED, that guaranteed payments be made to the following partners:\n\n[Partner Name] - $[Amount]" },
    { label: "Admit New Partner", statute: "Wis. Stat. § 178.0401", template: "RESOLVED, that ______ is admitted as a [general/limited] partner with a ______% interest, effective ______." },
    { label: "Approve Transfer of Partnership Interest", statute: "Wis. Stat. § 178.0503", template: "RESOLVED, that the transfer of ______% partnership interest from ______ to ______ is approved." },
    { label: "Approve Employment/Service Agreement", template: "RESOLVED, that the partnership is authorized to enter into a service agreement with ______." },
    { label: "Approve Lease Agreement", template: "RESOLVED, that the partnership is authorized to execute a lease for premises at ______." },
    { label: "Approve Purchase/Sale of Assets", template: "RESOLVED, that the partnership is authorized to [purchase/sell]: ______ for $______." },
    { label: "Ratify Prior Actions", template: "RESOLVED, that all acts and transactions of the partners since the last meeting are hereby ratified and approved." },
    { label: "Adopt Regular Meeting Resolution", template: "RESOLVED, that regular meetings of the partners shall be held on the ______ day of each ______ at ______ o'clock." },
    { label: "Approve Amendments to Partnership Agreement", template: "RESOLVED, that the Partnership Agreement is hereby amended as follows:\n\n______" },
    { label: "Approve Dissolution", statute: "Wis. Stat. § 178.0801", template: "RESOLVED, that the partnership is hereby authorized to dissolve and wind up its affairs in accordance with the Partnership Agreement and Wisconsin Statutes Chapter 178." },
    { label: "Other" },
  ],
};
