import jsPDF from "jspdf";

export interface StockCertificateData {
  companyName: string;
  stateOfIncorporation?: string;
  certificateNumber: number;
  shareholderName: string;
  numShares: number;
  shareClass: string;
  parValue?: number | null;
  issueDate: string;
  authorizedShares?: number | null;
}

export function generateStockCertificatePdf(data: StockCertificateData): jsPDF {
  const doc = new jsPDF({ orientation: "landscape" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();

  // Decorative border
  doc.setDrawColor(30, 60, 120);
  doc.setLineWidth(2);
  doc.rect(10, 10, pw - 20, ph - 20);
  doc.setLineWidth(0.5);
  doc.rect(14, 14, pw - 28, ph - 28);

  let y = 35;

  // Company name
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(data.companyName.toUpperCase(), pw / 2, y, { align: "center" });
  y += 10;

  if (data.stateOfIncorporation) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    doc.text(`Incorporated under the laws of the State of ${data.stateOfIncorporation}`, pw / 2, y, { align: "center" });
    y += 8;
  }

  if (data.authorizedShares) {
    doc.setFontSize(9);
    doc.text(`Authorized Shares: ${data.authorizedShares.toLocaleString()}`, pw / 2, y, { align: "center" });
    y += 8;
  }

  // Certificate header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 60, 120);
  doc.text("STOCK CERTIFICATE", pw / 2, y + 5, { align: "center" });
  y += 16;

  // Certificate number
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text(`Certificate No. ${data.certificateNumber}`, 30, y);
  doc.text(`${data.numShares.toLocaleString()} Shares`, pw - 30, y, { align: "right" });
  y += 12;

  // Main body
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const bodyText = `This certifies that ${data.shareholderName} is the registered holder of ${data.numShares.toLocaleString()} shares of ${data.shareClass} Stock${data.parValue ? ` (Par Value: $${data.parValue.toFixed(2)})` : ""} of ${data.companyName}, transferable only on the books of the Corporation by the holder hereof in person or by attorney upon surrender of this Certificate properly endorsed.`;

  const lines = doc.splitTextToSize(bodyText, pw - 80);
  doc.text(lines, pw / 2, y, { align: "center", maxWidth: pw - 80 });
  y += lines.length * 6 + 15;

  // Issue date
  doc.setFontSize(10);
  doc.text(`Issued: ${new Date(data.issueDate + "T00:00:00").toLocaleDateString()}`, pw / 2, y, { align: "center" });
  y += 20;

  // Signature lines
  const sigY = ph - 45;
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.3);
  doc.line(40, sigY, 120, sigY);
  doc.line(pw - 120, sigY, pw - 40, sigY);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Secretary", 80, sigY + 5, { align: "center" });
  doc.text("President", pw - 80, sigY + 5, { align: "center" });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by EntityIQ — Corporate Records Management", pw / 2, ph - 15, { align: "center" });

  return doc;
}

export function downloadStockCertificatePdf(data: StockCertificateData) {
  const doc = generateStockCertificatePdf(data);
  doc.save(`certificate-${data.certificateNumber}.pdf`);
}
