project_id = "spoljisxqqfiiyyutnab"

[functions.generate-record-book]
verify_jwt = false

[functions.generate-operating-agreement]
verify_jwt = false

[functions.generate-bylaws]
verify_jwt = false

[functions.generate-nonprofit-bylaws]
verify_jwt = false

[functions.parse-tax-return]
verify_jwt = false
